
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author student
 */
public class quiz extends javax.swing.JFrame {

    /**
     * Creates new form quiz
     */
    public quiz() {
        initComponents();
    }
    String name, contact, gender;
    int qs = 0;
    int correct = 0;
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("What is extension for java file?");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton1.setText(".c");
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton2.setText(".py");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton3.setText(".js");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 255, 255));
        jRadioButton4.setText(".java");

        jButton1.setFont(new java.awt.Font("Mongolian Baiti", 1, 18)); // NOI18N
        jButton1.setText("Next");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Vidyadhar epili\\Pictures\\template_for_quiz.jpg")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(144, 144, 144)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(374, 374, 374)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jRadioButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(jRadioButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(67, 67, 67)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(layout.createSequentialGroup()
                .addGap(267, 267, 267)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jLabel2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(qs==0){
            qs++;
            if(jRadioButton4.isSelected()){
                correct++;
            }
            jLabel1.setText("What is not a feature of OOPs?");
            jRadioButton1.setText("Exception Handling");
            jRadioButton2.setText("Encapsulation");
            jRadioButton3.setText("Polymorphism");
            jRadioButton4.setText("Inheritance");
        }
        else if(qs==1){
            qs++;
            if(jRadioButton1.isSelected()){
                
                correct++;
            }
            jLabel1.setText("What is not a data type in java?");
            jRadioButton1.setText("Integer");
            jRadioButton2.setText("List");
            jRadioButton3.setText("Character");
            jRadioButton4.setText("String");
        }
        else if(qs==2){
            qs++;
            if(jRadioButton2.isSelected()){
                correct++;
            }
            jLabel1.setText("<html>What is used to insert a single <br>line comment in java?</html>");
            jRadioButton1.setText("#");
            jRadioButton2.setText("/*");
            jRadioButton3.setText("//");
            jRadioButton4.setText("<!-->");
        }
        else if(qs==3){
            qs++;
            if(jRadioButton3.isSelected()){
                correct++;
            }
            jLabel1.setText("<html>Which method can be used to find <br>the length of a string?</html>");
            jRadioButton1.setText("getSize()");
            jRadioButton2.setText("length()");
            jRadioButton3.setText("len()");
            jRadioButton4.setText("getLength()");
        }
        else if(qs==4){
            qs++;
            if(jRadioButton2.isSelected()){
                correct++;
            }
            jLabel1.setText("<html>Which method is used to find <br>the highest value of x and y?</html>");
            jRadioButton1.setText("Math.max()");
            jRadioButton2.setText("Math.maximum()");
            jRadioButton3.setText("Math.largest()");
            jRadioButton4.setText("Math.greater()");
        }
        else if(qs==5){
            qs++;
            if(jRadioButton1.isSelected()){
                correct++;
            }
            jLabel1.setText("What is the size of int variable?");
            jRadioButton1.setText("2 bytes");
            jRadioButton2.setText("16 bytes");
            jRadioButton3.setText("4 bytes");
            jRadioButton4.setText("8 bytes");
        }
        else if(qs==6){
            qs++;
            if(jRadioButton3.isSelected()){
                correct++;
            }
            jLabel1.setText("What is the default value of int variable?");
            jRadioButton1.setText("0.0");
            jRadioButton2.setText("null");
            jRadioButton3.setText("not defined");
            jRadioButton4.setText("0");
        }
        else if(qs==7){
            qs++;
            if(jRadioButton4.isSelected()){
                correct++;
            }
            jLabel1.setText("Which among them is not a class?");
            jRadioButton1.setText("Swing");
            jRadioButton2.setText("ActionPerformed");
            jRadioButton3.setText("Button");
            jRadioButton4.setText("ActionEvent");
        }
        else if(qs==8){
            qs++;
            if(jRadioButton2.isSelected()){
                correct++;
            }
            jLabel1.setText("<html>Which of the below is not a keyword <br>in java?</html>");
            jRadioButton1.setText("int");
            jRadioButton2.setText("finally");
            jRadioButton3.setText("switch");
            jRadioButton4.setText("get");
        }
        else if(qs==9){
            if(jRadioButton4.isSelected()){
                correct++;
            } 
            insert_values();
            String[] options = {"Play Again","Exit"};
            
            int result = JOptionPane.showOptionDialog(this,name+", your score is "+correct+" out of 10","Result",JOptionPane.YES_NO_OPTION,JOptionPane.PLAIN_MESSAGE,null,options,options[0]);
            if (result== JOptionPane.YES_OPTION){
                login obj = new login();
                obj.setVisible(true);
                this.dispose();
            }
            else if(result == JOptionPane.NO_OPTION){
                System.exit(0);
            }
            
        }
        buttonGroup1.clearSelection();
    }//GEN-LAST:event_jButton1ActionPerformed
public void insert_values(){
              Connection con = null;
        try{
            Class.forName("com.mysql.cj.jdbc.Driver");    
            System.out.println("Welcome");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/java_projects","root","root");
            System.out.println("Connection Created");
            String s = "insert into quiz(name, score, contact, gender) values(?,?,?,?)";
            PreparedStatement ps = con.prepareStatement(s);
            ps.setString(1, name);
            ps.setString(2, ""+correct);
            ps.setString(3, contact);
            ps.setString(4, gender);
            ps.execute();
            con.close();
        }
        catch(Exception e){
            System.out.println("Exception Occured");    
            System.out.println("Exception "+e);
        }
          }
     
        
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(quiz.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new quiz().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
